### ISSUE TITLE
Implement docker security processes

### ISSUE THREAD

**Issue by Tansito** [Qiskit-Extensions/quantum-serverless#690]
### What is the expected behaviour?

With the purpose to accomplish all our requirements from a security point of view we are going to implement the next features:

- [x] Docker lint with `hadolint` ( ref #689 )
- [x] SAST check with `conftest` ( ref #696 )
- [ ] VSCAN using `trivy` ( ref #715 )
